# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: PocPoc
# Description of the Site
description: from the idea to the proof of concept
# URL of Image of the Site
site-image: /WhatATheme/assets/images/logo.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://github.com/Alex-system/pocpoc.github.io/blob/master/assets/images/logo.png?raw=true

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://github.com/Alex-system/pocpoc.github.io/blob/master/assets/images/drone.jpg?raw=true&auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
#assets/images/drone.jpg
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: alex@pocpoc.tech
#instagram_username: 
linkedin_username: alexandresusbielle
github_username:  alex-system
youtube_channel_id: UCa6DfoA4BCT_ENMSYM43gCg


# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: PocPoc

# Name of the Author
author-name: PocPoc
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: PocPoc provide a service based on an automated UAV for maritime intervention as boat inspection, bathymetry or ports data management.The use of automated drone, custom made for these use cases allow any operations be safer, more efficient and doable in any condition.We already worked with S&R professionals for more than 2 years (SNSM, firemen, Lifeguards) they were heavily involved in the product development.We took into account their work procedures, their specific needs and their expertise about the definition of the use case.This previous partnership allows PocPoc to offer a very efficient solution for both coastguard and any maritime interventions. The close work with sea rescue SNSM bring our attention on an alternate need for a simple to use automated UAV, the UAV could be a decisive tool for operations at sea! We also realise that this powerful and versatile tool could be use in a lot of scenarios other than search and rescue.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Alex-system

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      path: "/WhatATheme/assets/images"
    values:
      image: true
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
